/**
 * Build script: generate the installable agent preset under `preset/orchestrator/`.
 *
 * The preset is a self-contained DSH agent-preset directory:
 *
 *   preset/orchestrator/
 *   ├── agent.cordis.yml       (the composition, generated from src + prompts)
 *   ├── preset.yml             (display metadata)
 *   └── orchestration.mjs      (the boundary row, copied from src)
 *
 * Installation is a plain directory copy into `$DSH_HOME/.agent-presets/`.
 *
 * Run: node scripts/build.mjs
 *
 * @module multi-agent-orchestrator/scripts/build
 */

import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { SPECIALISTS } from "../src/agents/catalog.js";
import { AGENT_INSTRUCTIONS_MAX_BYTES, PRESET_ID, PRESET_METADATA } from "../src/config/defaults.js";
import { loadModelRouting } from "../src/config/model-routing.js";
import { loadOrchestratorPersona, loadSpecialistPersona } from "../src/config/loader.js";
import { shellTool } from "../src/permissions/agent-permissions.js";
import { assertAgentDefinition } from "../src/config/schema.js";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const PRESET_DIR = join(ROOT, "preset", PRESET_ID);

/** YAML-safe string: must not contain control chars; block scalars handle the rest. */
function blockScalar(text, indent) {
	const pad = " ".repeat(indent);
	const lines = text.replace(/\r\n/g, "\n").split("\n");
	// Keep trailing newline semantics simple: literal block, no strip marker.
	return lines.map((line) => (line === "" ? "" : `${pad}${line}`)).join("\n");
}

/**
 * Render the toolFilter for one specialist as platform-conditional YAML.
 *
 * The `!!js` expression MUST be a quoted scalar: the loader parses
 * agent.cordis.yml with js-yaml's JSON_SCHEMA + the JsExpr type, and an
 * unquoted plain scalar containing `[`/`]`/`?` breaks plain-scalar parsing.
 * The expression uses single quotes inside, so double-quoted YAML works.
 * @param {object} specialist - the specialist definition.
 * @returns {string} YAML for `toolFilter`.
 */
function renderToolFilter(specialist) {
	const posix = specialist.filterFor("posix");
	const win32 = specialist.filterFor("win32");
	const same = JSON.stringify(posix.allow) === JSON.stringify(win32.allow);
	if (same) {
		return [
			"    toolFilter:",
			`      allow: ${JSON.stringify(posix.allow)}`
		].join("\n");
	}
	const expr = `process.platform === 'win32' ? ${JSON.stringify(win32.allow)} : ${JSON.stringify(posix.allow)}`;
	return [
		"    toolFilter:",
		`      allow: !!js "${expr.replaceAll('"', '\\"')}"`
	].join("\n");
}

/**
 * Render one delegation tool row.
 * @param {object} specialist - the specialist definition.
 * @param {string} persona - the specialist's system prompt.
 * @param {object} [modelRoute] - optional per-specialist agentOptions
 *   `{ provider, model, maxTokens }` from model-routing.json.
 * @returns {string} YAML row text.
 */
function renderDelegationRow(specialist, persona, modelRoute) {
	const lines = [
		`- id: tool-subagent-${specialist.id}`,
		"  name: '@deepseek-ai/dsh-tool-subagent'",
		"  config:",
		"    provider: spawn",
		`    toolName: ${specialist.toolName}`,
		"    enableRunInBackground: false",
		"    backgroundMode: one-shot",
		`    maxDepth: ${specialist.maxDepth}`,
		"    persona: |",
		blockScalar(persona, 10),
		renderToolFilter(specialist)
	];
	if (modelRoute !== void 0) {
		lines.push("    agentOptions:",
			`      provider: ${modelRoute.provider}`,
			`      model: ${modelRoute.model}`,
			`      maxTokens: ${modelRoute.maxTokens}`);
	}
	return lines.join("\n");
}

/**
 * Compose the full agent.cordis.yml text.
 * @returns {string} the composition YAML.
 */
export function renderComposition() {
	const orchestratorPersona = loadOrchestratorPersona(ROOT);
	const modelRoutes = loadModelRouting(ROOT);
	const rows = [];
	rows.push("# The `orchestrator` agent preset: multi-agent orchestration mode.");
	rows.push("#");
	rows.push("# GENERATED BY scripts/build.mjs — edit src/ and prompts/, then rebuild.");
	rows.push("#");
	rows.push("# The session agent is the Orchestrator (control plane). The six");
	rows.push("# specialist tools below spawn role-isolated subagents: each child gets");
	rows.push("# its own persona, its own toolFilter (compiled into tools.restrict()"),
	rows.push("# on the child's scope), and maxDepth 1, so a specialist can never");
	rows.push("# spawn another agent. The orchestration row narrows the root agent's");
	rows.push("# own tools at agent/created.");
	rows.push("");
	rows.push("# ── identity ────────────────────────────────────────────────────────");
	rows.push("");
	rows.push("- id: persona");
	rows.push("  name: '@deepseek-ai/dsh-persona'");
	rows.push("  config:");
	rows.push("    text: |");
	rows.push(blockScalar(orchestratorPersona, 6));
	rows.push("    complete: true");
	rows.push("");
	rows.push("- id: agent-instructions");
	rows.push("  name: '@deepseek-ai/dsh-agent-instructions'");
	rows.push("  config:");
	rows.push(`    maxBytes: ${AGENT_INSTRUCTIONS_MAX_BYTES}`);
	rows.push("");
	rows.push("# ── shell ───────────────────────────────────────────────────────────");
	rows.push("");
	rows.push("- id: tool-bash");
	rows.push("  name: '@deepseek-ai/dsh-tool-bash'");
	rows.push("  disabled: !!js process.platform === 'win32'");
	rows.push("");
	rows.push("- id: tool-pwsh");
	rows.push("  name: '@deepseek-ai/dsh-tool-pwsh'");
	rows.push("  disabled: !!js process.platform !== 'win32'");
	rows.push("");
	rows.push("# ── filesystem and search ───────────────────────────────────────────");
	rows.push("");
	rows.push("- id: tool-fs");
	rows.push("  name: '@deepseek-ai/dsh-tool-fs'");
	rows.push("");
	rows.push("- id: tool-fs-search");
	rows.push("  name: '@deepseek-ai/dsh-tool-fs-search'");
	rows.push("  config:");
	rows.push("    sampleOverCapGlobResults: false");
	rows.push("");
	rows.push("# ── background jobs ─────────────────────────────────────────────────");
	rows.push("");
	rows.push("- id: tool-jobs");
	rows.push("  name: '@deepseek-ai/dsh-tool-jobs'");
	rows.push("");
	rows.push("# ── model-facing rows ───────────────────────────────────────────────");
	rows.push("");
	rows.push("- id: tool-ask-user");
	rows.push("  name: '@deepseek-ai/dsh-tool-ask-user'");
	rows.push("");
	rows.push("- id: tool-todo");
	rows.push("  name: '@deepseek-ai/dsh-tool-todo'");
	rows.push("  config:");
	rows.push("    allowParallelInProgress: true");
	rows.push("");
	rows.push("- id: tool-web");
	rows.push("  name: '@deepseek-ai/dsh-tool-web'");
	rows.push("  config:");
	rows.push("    fetch: false");
	rows.push("    searchTimeoutMs: 60000");
	rows.push("");
	rows.push("# The child catalog tool: the Orchestrator can list its specialists.");
	rows.push("- id: tool-subagent-list-agents");
	rows.push("  name: '@deepseek-ai/dsh-tool-subagent-control/list-agents'");
	rows.push("");
	rows.push("# ── delegation: the six specialists ─────────────────────────────────");
	rows.push("");
	for (const specialist of SPECIALISTS) {
		const persona = loadSpecialistPersona(ROOT, specialist);
		const modelRoute = modelRoutes[specialist.id];
		rows.push(renderDelegationRow(specialist, persona, modelRoute));
		rows.push("");
	}
	rows.push("# ── control-plane boundary ──────────────────────────────────────────");
	rows.push("");
	rows.push("- id: orchestration");
	rows.push("  name: ./orchestration.mjs");
	rows.push("");
	rows.push("# ── compaction ──────────────────────────────────────────────────────");
	rows.push("");
	rows.push("- id: compaction");
	rows.push("  name: cordis:group");
	rows.push("  group: true");
	rows.push("  isolate:");
	rows.push("    compaction: true");
	rows.push("    toolResultPruner: true");
	rows.push("  config:");
	rows.push("    - id: compaction-basic");
	rows.push("      name: '@deepseek-ai/dsh-compaction-basic'");
	rows.push("");
	rows.push("    - id: command-compact");
	rows.push("      name: '@deepseek-ai/dsh-command-compact'");
	rows.push("");
	rows.push("    - id: tool-result-pruner");
	rows.push("      name: '@deepseek-ai/dsh-compaction-tool-result-pruner'");
	rows.push("      config:");
	rows.push("        thresholdChars: 8192");
	rows.push("        headChars: 4096");
	rows.push("        tailChars: 1024");
	rows.push("");
	return rows.join("\n");
}

/**
 * Render preset.yml (display metadata).
 * @returns {string} the metadata YAML.
 */
export function renderPresetMetadata() {
	const lines = [
		`name: ${PRESET_METADATA.name}`,
		`description: ${PRESET_METADATA.description}`,
		`order: ${PRESET_METADATA.order}`
	];
	return lines.join("\n");
}

/**
 * Validate and write the generated preset directory.
 * @returns {string[]} paths written.
 */
export function build() {
	for (const specialist of SPECIALISTS) {
		assertAgentDefinition(specialist, `specialist:${specialist.id}`);
	}
	mkdirSync(PRESET_DIR, { recursive: true });
	const compositionPath = join(PRESET_DIR, "agent.cordis.yml");
	const metadataPath = join(PRESET_DIR, "preset.yml");
	const rowPath = join(PRESET_DIR, "orchestration.mjs");
	writeFileSync(compositionPath, renderComposition(), "utf8");
	writeFileSync(metadataPath, renderPresetMetadata() + "\n", "utf8");
	copyFileSync(join(ROOT, "src", "orchestration", "orchestration.mjs"), rowPath);
	return [compositionPath, metadataPath, rowPath];
}

// Allow both `import { build }` (tests) and `node scripts/build.mjs`.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
	const written = build();
	console.log(`built ${PRESET_ID} preset:`);
	for (const path of written) console.log(`  ${path}`);
}
