/**
 * Build the trajectory-counter client bundle.
 *
 * Assembles `client/trajectory-counter/client/client.js` (the file the host's
 * client-module scanner serves at `/plugins/dsh-trajectory-counter/client.js`)
 * from:
 *   - `src/classify.js`     — pure classifier (ESM; `export ` stripped so the
 *     functions land in the factory scope);
 *   - `src/component.cjs`   — the React component + plugin body (CJS, uses
 *     `require` for react / the client runtime).
 *
 * The output follows the exact `window.__ModuleLoader__.load({ id, factory })
 * shape of the official client plugins. The committed bundle is
 * reproducibility-checked by `tests/client-bundle.test.mjs`.
 *
 * Run: node scripts/build-client.mjs
 *
 * @module dsh-trajectory-counter/scripts/build-client
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const PKG_DIR = join(ROOT, "client", "trajectory-counter");
const SRC = join(PKG_DIR, "src");
const OUT = join(PKG_DIR, "client", "client.js");

const PKG = JSON.parse(readFileSync(join(PKG_DIR, "package.json"), "utf8"));

/** Inline the ESM classifier into the CJS factory scope (strip `export `). */
function inlineClassifier() {
	const source = readFileSync(join(SRC, "classify.js"), "utf8");
	const body = source
		.replace(/^\/\*\*[\s\S]*?\*\/\n/gm, "") // drop the module doc comment
		.replace(/^export /gm, "");
	return body.split("\n").map((line) => `\t${line}`).join("\n");
}

/** The component + plugin body, indented to sit inside the factory. */
function inlineComponent() {
	const source = readFileSync(join(SRC, "component.cjs"), "utf8");
	// Strip the leading module doc comment (kept only in the source file).
	const body = source.replace(/^\/\*\*[\s\S]*?\*\/\n/, "");
	return body.split("\n").map((line) => `\t${line}`).join("\n");
}

/** Assemble the full browser bundle. */
export function buildClientBundle() {
	const lines = [
		"// GENERATED BY scripts/build-client.mjs — do not edit; edit src/ and rebuild.",
		"window.__ModuleLoader__.load({",
		`\tid: ${JSON.stringify(PKG.name)},`,
		"\tfactory: (require) => {",
		"\t\tvar module = { exports: {} };",
		"\t\tvar exports = module.exports;",
		"\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: \"Module\" });",
		inlineClassifier(),
		inlineComponent(),
		"\t\treturn module.exports;",
		"\t}",
		"});",
		""
	];
	return lines.join("\n");
}

export function buildClient() {
	mkdirSync(dirname(OUT), { recursive: true });
	const bundle = buildClientBundle();
	writeFileSync(OUT, bundle, "utf8");
	return OUT;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	const path = buildClient();
	console.log(`built trajectory-counter client bundle → ${path} (${readFileSync(path, "utf8").length} chars)`);
}
